import '@/styles/globals.css'
import Head from 'next/head';
import { useConter } from '@/hooks/useConter'
import { useInputArray } from '@/hooks/useInputArra'
import { useBglightBlue } from '@/hooks/useBglightBlue'




export default function App({ Component, pageProps }) {
  const conter = useConter();
  const InputArray = useInputArray();
  useBglightBlue();


  return (
  <>
     <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
    <Component {...pageProps} {...conter} {...InputArray}/>
  </>
  );
}
